name: Build and Scan Docker Image

on:
  #push:
  #  branches: [master]
  #pull_request:
  workflow_dispatch: # Permette di avviare il workflow manualmente dalla UI di GitHub

jobs:
  build-and-scan:
    secrets: inherit
    uses: Neomediatech/docker-images-scan-reports/.github/workflows/build-and-scan-docker-image.yml@main
    with:
      dockerfile: "Dockerfile"
      dockerdir: "."
      dockertag: "latest"

  push-report-to-repo:
    needs: [build-and-scan]
    secrets: inherit
    uses: Neomediatech/docker-images-scan-reports/.github/workflows/copy-file-to-another-repo.yml@main
    with:
      file_id: ${{ needs.build-and-scan.outputs.uploaded-file-id }}
      filename: ${{ needs.build-and-scan.outputs.file_to_copy_output }}
